Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/LiteralComment:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Metrics/LineLength:
  Max: 100

AllCops:
  Exclude:
    - 'db/**/*'
